### ISSUE TITLE
✨ user, product 서비스와 연결

### ISSUE THREAD

**Issue by puclpu** [fcfs-commerce/order#5]
#### Description
user, product 서비스와 통신하여 기존의 order api가 작동하도록 수정

#### Todo
- [x] User 서비스와 통신
  - [x] 사용자 이름 조회
- [x] Product 서비스와 통신
  - [x] 재고 변경, optionItem 정보 조회
- [x] 주문 내역, 주문 내역 목록 조회

#### ETC
